### ISSUE TITLE
Crash after accepting permissions

### ISSUE THREAD

**Issue by keith24** [Tracman-org/Android#12]

**Comment by keith24** [comment]
Logs provide:

```java
05-06 16:30:50.826 27719-27813/us.keithirwin.tracman E/EventThread: Task threw exception
                                                                    java.lang.IllegalStateException: Can't create handler inside thread that has not called Looper.prepare()
                                                                        at com.google.android.gms.common.internal.zzaa.zza(Unknown Source)
                                                                        at com.google.android.gms.location.internal.zzk$zzc.<init>(Unknown Source)
                                                                        at com.google.android.gms.location.internal.zzk.zza(Unknown Source)
                                                                        at com.google.android.gms.location.internal.zzk.zza(Unknown Source)
                                                                        at com.google.android.gms.location.internal.zzl.zza(Unknown Source)
                                                                        at com.google.android.gms.location.internal.zzd$1.zza(Unknown Source)
                                                                        at com.google.android.gms.location.internal.zzd$1.zza(Unknown Source)
                                                                        at com.google.android.gms.internal.zzqo$zza.zzb(Unknown Source)
                                                                        at com.google.android.gms.internal.zzra.zzd(Unknown Source)
                                                                        at com.google.android.gms.internal.zzra.zzb(Unknown Source)
                                                                        at com.google.android.gms.internal.zzrf.zzb(Unknown Source)
                                                                        at com.google.android.gms.internal.zzrd.zzb(Unknown Source)
                                                                        at com.google.android.gms.location.internal.zzd.requestLocationUpdates(Unknown Source)
                                                                        at us.keithirwin.tracman.LocationService.connectLocationUpdates(LocationService.java:223)
                                                                        at us.keithirwin.tracman.LocationService$4.call(LocationService.java:273)
                                                                        at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                        at io.socket.client.Socket.onevent(Socket.java:340)
                                                                        at io.socket.client.Socket.onpacket(Socket.java:293)
                                                                        at io.socket.client.Socket.access$100(Socket.java:19)
                                                                        at io.socket.client.Socket$2$2.call(Socket.java:111)
                                                                        at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                        at io.socket.client.Manager.ondecoded(Manager.java:407)
                                                                        at io.socket.client.Manager.access$1600(Manager.java:20)
                                                                        at io.socket.client.Manager$7.call(Manager.java:383)
                                                                        at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                        at io.socket.parser.Parser$Decoder.add(Parser.java:157)
                                                                        at io.socket.client.Manager.ondata(Manager.java:399)
                                                                        at io.socket.client.Manager.access$1000(Manager.java:20)
                                                                        at io.socket.client.Manager$2.call(Manager.java:350)
                                                                        at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                        at io.socket.engineio.client.Socket.onPacket(Socket.java:511)
                                                                        at io.socket.engineio.client.Socket.access$1000(Socket.java:31)
                                                                        at io.socket.engineio.client.Socket$5.call(Socket.java:313)
                                                                        at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                        at io.socket.engineio.client.Transport.onPacket(Transport.java:134)
                                                                        at io.socket.engineio.client.Transport.onData(Transport.java:126)
                                                                        at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
                                                                        at io.socket.engineio.client.transports.WebSocket$2$2.run(WebSocket.java:99)
                                                                        at io.socket.thread.EventThread$2.run(EventThread.java:80)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                        at java.lang.Thread.run(Thread.java:818)
05-06 16:30:50.831 27719-27813/us.keithirwin.tracman E/AndroidRuntime: FATAL EXCEPTION: EventThread
                                                                       Process: us.keithirwin.tracman, PID: 27719
                                                                       java.lang.IllegalStateException: Can't create handler inside thread that has not called Looper.prepare()
                                                                           at com.google.android.gms.common.internal.zzaa.zza(Unknown Source)
                                                                           at com.google.android.gms.location.internal.zzk$zzc.<init>(Unknown Source)
                                                                           at com.google.android.gms.location.internal.zzk.zza(Unknown Source)
                                                                           at com.google.android.gms.location.internal.zzk.zza(Unknown Source)
                                                                           at com.google.android.gms.location.internal.zzl.zza(Unknown Source)
                                                                           at com.google.android.gms.location.internal.zzd$1.zza(Unknown Source)
                                                                           at com.google.android.gms.location.internal.zzd$1.zza(Unknown Source)
                                                                           at com.google.android.gms.internal.zzqo$zza.zzb(Unknown Source)
                                                                           at com.google.android.gms.internal.zzra.zzd(Unknown Source)
                                                                           at com.google.android.gms.internal.zzra.zzb(Unknown Source)
                                                                           at com.google.android.gms.internal.zzrf.zzb(Unknown Source)
                                                                           at com.google.android.gms.internal.zzrd.zzb(Unknown Source)
                                                                           at com.google.android.gms.location.internal.zzd.requestLocationUpdates(Unknown Source)
                                                                           at us.keithirwin.tracman.LocationService.connectLocationUpdates(LocationService.java:223)
                                                                           at us.keithirwin.tracman.LocationService$4.call(LocationService.java:273)
                                                                           at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                           at io.socket.client.Socket.onevent(Socket.java:340)
                                                                           at io.socket.client.Socket.onpacket(Socket.java:293)
                                                                           at io.socket.client.Socket.access$100(Socket.java:19)
                                                                           at io.socket.client.Socket$2$2.call(Socket.java:111)
                                                                           at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                           at io.socket.client.Manager.ondecoded(Manager.java:407)
                                                                           at io.socket.client.Manager.access$1600(Manager.java:20)
                                                                           at io.socket.client.Manager$7.call(Manager.java:383)
                                                                           at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                           at io.socket.parser.Parser$Decoder.add(Parser.java:157)
                                                                           at io.socket.client.Manager.ondata(Manager.java:399)
                                                                           at io.socket.client.Manager.access$1000(Manager.java:20)
                                                                           at io.socket.client.Manager$2.call(Manager.java:350)
                                                                           at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                           at io.socket.engineio.client.Socket.onPacket(Socket.java:511)
                                                                           at io.socket.engineio.client.Socket.access$1000(Socket.java:31)
                                                                           at io.socket.engineio.client.Socket$5.call(Socket.java:313)
                                                                           at io.socket.emitter.Emitter.emit(Emitter.java:117)
                                                                           at io.socket.engineio.client.Transport.onPacket(Transport.java:134)
                                                                           at io.socket.engineio.client.Transport.onData(Transport.java:126)
                                                                           at io.socket.engineio.client.transports.WebSocket.access$100(WebSocket.java:24)
                                                                           at io.socket.engineio.client.transports.WebSocket$2$2.run(WebSocket.java:99)
                                                                           at io.socket.thread.EventThread$2.run(EventThread.java:80)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                           at java.lang.Thread.run(Thread.java:818)
```

**Comment by keith24** [comment]
This doesn't seem to be an issue when the app is installed from the play store.
